- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 6000
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  #start-backmen: currency
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: Command
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      - type: PsionicBonusChance
        flatBonus: 0.025
      - type: NpcFactionMember
        factions:
          - CentralCommand
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
